catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  ai-kit:
    '@vue-flow/background': ^1.3.2
    '@vue-flow/controls': ^1.1.3
    '@vue-flow/core': ^1.48.0
    '@vue-flow/node-toolbar': ^1.1.1
    ai: ^5.0.107
    shiki: ^3.19.0
    tokenlens: ^1.3.1

  docs-app:
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/lucide': ^1.2.78
    '@iconify-json/simple-icons': ^1.2.61
    baseline-browser-mapping: ^2.9.2
    highlight.js: ^11.11.1
    nuxt: 3.18.0
    shadcn-docs-nuxt: ^1.1.7

  server-runtime:
    '@modelcontextprotocol/sdk': ^1.24.3
    h3: ^1.15.4
    nitropack: ^2.12.9
    wrangler: ^4.52.1

  shared:
    nanoid: ^5.1.6

  testing:
    '@vitest/browser-playwright': ^4.0.14
    '@vitest/ui': 4.0.15
    '@vue/test-utils': ^2.4.6
    playwright: ^1.57.0
    vitest: ^4.0.15
    vitest-browser-vue: ^2.0.1

  tooling:
    '@antfu/eslint-config': ^6.4.2
    '@commitlint/cli': ^20.2.0
    '@commitlint/config-conventional': ^20.2.0
    '@tailwindcss/vite': ^4.1.17
    '@types/hast': ^3.0.4
    '@vitejs/plugin-vue': ^6.0.2
    '@vitejs/plugin-vue-jsx': ^5.1.2
    '@vue/compiler-sfc': ^3.5.25
    bumpp: ^10.3.2
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    ts-morph: ^27.0.2
    turbo: ^2.6.3
    typescript: ^5.9.3

  ui-core:
    '@tanstack/vue-table': ^8.21.3
    '@unovis/ts': ^1.6.2
    '@unovis/vue': ^1.6.2
    '@vueuse/core': ^14.1.0
    '@vueuse/shared': ^14.1.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    embla-carousel-vue: ^8.6.0
    lucide-vue-next: ^0.555.0
    motion-v: ^1.7.4
    reka-ui: ^2.6.1
    shadcn-nuxt: 2.4.1
    shadcn-vue: ^2.4.1
    streamdown-vue: ^1.0.29
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.17
    tailwindcss-animate: ^1.0.7
    tw-animate-css: ^1.4.0
    vaul-vue: ^0.4.1
    vue: ^3.5.25
    vue-router: ^4.6.3
    vue-sonner: ^2.0.9
    vue-stick-to-bottom: ^0.1.0

  validation:
    '@vee-validate/zod': ^4.15.1
    vee-validate: ^4.15.1
    zod: ^4.1.13

allowedDeprecatedVersions:
  '@oxc-parser/wasm': 0.60.0
  '@types/parse-path': 7.1.0
  glob: 7.2.3
  inflight: 1.0.6
  node-domexception: 1.0.0
  source-map-resolve: 0.6.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - maplibre-gl
  - sharp
  - simple-git-hooks
  - vue-demi
  - workerd

peerDependencyRules:
  allowedVersions:
    zod: '4'
